# Set user PATH
typeset -U PATH path
path=("$HOME/.local/bin" "$path[@]")
export PATH

# User Environment Variables
export EDITOR=vim
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export SDL_IM_MODULE=ibus
export GLFW_IM_MODULE=ibus
export DOTNET_CLI_TELEMETRY_OUTPUT=1
