" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
    \| PlugInstall --sync | source $MYVIMRC
\| endif

" Begin loading plugins
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
Plug 'jiangmiao/auto-pairs'
Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'yggdroot/indentline'
call plug#end()

" General options
filetype plugin indent on

set number
set mouse =a
set noerrorbells

" IndentLine specific options
let g:indentLine_char ='│'
let g:indentLine_color_term ='0'
let g:indentLine_leadingSpaceChar ='·'
let g:indentLine_leadingSpaceEnabled =1

" NERDTree specific options
" autocmd StdinReadPre * let s:std_in = 1
" autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif
" autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

nnoremap <F5> :NERDTreeToggle<CR>

let NERDTreeShowHidden =1

" Vim Airline specific options
let g:airline_powerline_fonts =1
set noshowmode
set ttimeoutlen =10

" Color settings
syntax enable
set colorcolumn =120
colorscheme nord
set background =dark

" Swap/Backup settings
set nobk
set nowb
set noswapfile

"""""""""""""""""""""""
" Formatting settings
"""""""""""""""""""""""
set ffs =unix,dos,mac
set expandtab
set smarttab
set shiftwidth =3
set tabstop =3
set ai
set si
set nowrap
